name = "ReadSniper"
uuid = "65349bb5-18ff-45c8-b309-cf102ab866d8"
authors = ["Periareion"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
